version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: koa
      MONGO_INITDB_ROOT_PASSWORD: koa
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: koakoatutorial
      MYSQL_DATABASE: koa
      MYSQL_USER: koa-tutorial
      MYSQL_PASSWORD: koa-tutorial
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
  node-app:
    build:
      context: .
      dockerfile: ./dockerfiles/node.16.19.1.alpine.3.16.Dockerfile
    command: "node app.js api -p"
    depends_on:
      - db
      - mongodb
    ports:
      - ${KOA_PORT_EXTERNAL}:${KOA_PORT}
    volumes:
      - type: bind
        source: ${KOA_WORKSPACE}/${KOA_PROJECT_NAME}
        target: /code
      - type: bind
        source: ${SSH_PUBLIC_KEYS_DIR}
        target: /root/.ssh
      - type: bind
        source: ${SSH_PUBLIC_KEYS_DIR}
        target: /home/node/.ssh
      - ${NODEJS_BUILD_FOLDER}:${NODEJS_BUILD_INTERNAL_FOLDER}
  localstack:
    image: localstack/localstack:latest
    environment:
      SERVICES: s3
      DEBUG: 1
      DEFAULT_REGION: us-east-1
      DATA_DIR: /tmp/localstack/data
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
    ports:
      - 4566:4566
    volumes:
      - ./localstack_tmp:/tmp/localstack
